//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _MFTP_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Recent : global::System.Configuration.ApplicationSettingsBase {
        
        private static Recent defaultInstance = ((Recent)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Recent())));
        
        public static Recent Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Recent_IP {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Recent_IP"]));
            }
            set {
                this["Recent_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Recent_Login {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Recent_Login"]));
            }
            set {
                this["Recent_Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Recent_Pass {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Recent_Pass"]));
            }
            set {
                this["Recent_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Recent_Port {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Recent_Port"]));
            }
            set {
                this["Recent_Port"] = value;
            }
        }
    }
}
