//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _MFTP_.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_MFTP_.Resources.Localizations.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на null.
        /// </summary>
        public static string _null {
            get {
                return ResourceManager.GetString("null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access denied!.
        /// </summary>
        public static string Error_AccessDenied {
            get {
                return ResourceManager.GetString("Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad address. Write address same: &quot;C:/Users/Admin/Desktop&quot;.
        /// </summary>
        public static string Error_BadAddress {
            get {
                return ResourceManager.GetString("Error_BadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port is incorrect!.
        /// </summary>
        public static string Error_BadPort {
            get {
                return ResourceManager.GetString("Error_BadPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This port is can&apos;t be saved..
        /// </summary>
        public static string Error_BadPortSave {
            get {
                return ResourceManager.GetString("Error_BadPortSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection refused. Check your Username or Password..
        /// </summary>
        public static string Error_Connection_Refused {
            get {
                return ResourceManager.GetString("Error_Connection_Refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection refused..
        /// </summary>
        public static string Error_Connection_Refused_Simple {
            get {
                return ResourceManager.GetString("Error_Connection_Refused_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This directory/file is not found..
        /// </summary>
        public static string Error_DirFileNotFound {
            get {
                return ResourceManager.GetString("Error_DirFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default folder isn&apos;t detected... Redirecting to disk list..
        /// </summary>
        public static string Error_EmptyAddress {
            get {
                return ResourceManager.GetString("Error_EmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder error..
        /// </summary>
        public static string Error_FolderError {
            get {
                return ResourceManager.GetString("Error_FolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, input correct IP Address..
        /// </summary>
        public static string Error_Incorrect_IP {
            get {
                return ResourceManager.GetString("Error_Incorrect_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server is unavailable. Connection has been closed..
        /// </summary>
        public static string Error_IsntConnected {
            get {
                return ResourceManager.GetString("Error_IsntConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One of this files or directories can&apos;t be deleted.(named as &quot;..&quot; or same exception).
        /// </summary>
        public static string Error_IsntDeleted {
            get {
                return ResourceManager.GetString("Error_IsntDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One of this files or directories can&apos;t be downloaded(named as &quot;..&quot; or same exception).
        /// </summary>
        public static string Error_IsntDownloaded {
            get {
                return ResourceManager.GetString("Error_IsntDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One of this files or directories can&apos;t be copied/moved(named as &quot;..&quot; or same exception).
        /// </summary>
        public static string Error_IsntMoved {
            get {
                return ResourceManager.GetString("Error_IsntMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File/Folder is can&apos;t be open now!.
        /// </summary>
        public static string Error_IsntOpened {
            get {
                return ResourceManager.GetString("Error_IsntOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This file or directory can&apos;t be renamed..
        /// </summary>
        public static string Error_IsntRenamed {
            get {
                return ResourceManager.GetString("Error_IsntRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One of this files or directories can&apos;t be uploaded(named as &quot;..&quot; or same exception).
        /// </summary>
        public static string Error_IsntUpload {
            get {
                return ResourceManager.GetString("Error_IsntUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moving error..
        /// </summary>
        public static string Error_MovingError {
            get {
                return ResourceManager.GetString("Error_MovingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write correct port from 0 to 65535!.
        /// </summary>
        public static string Error_PortOutOfRange {
            get {
                return ResourceManager.GetString("Error_PortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Refreshing is unavailable..
        /// </summary>
        public static string Error_RefreshingUnavailable {
            get {
                return ResourceManager.GetString("Error_RefreshingUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client isn&apos;t connected to server. Refreshing is unavalable..
        /// </summary>
        public static string Error_RefreshingUnavailableServer {
            get {
                return ResourceManager.GetString("Error_RefreshingUnavailableServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Please, select disk..
        /// </summary>
        public static string Error_SelectDisk {
            get {
                return ResourceManager.GetString("Error_SelectDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select disk or folder to download files/folders!.
        /// </summary>
        public static string Error_SelectDiskToDownload {
            get {
                return ResourceManager.GetString("Error_SelectDiskToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unexcepted error. Setting folder to default..
        /// </summary>
        public static string Error_SettingAddressDefault {
            get {
                return ResourceManager.GetString("Error_SettingAddressDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection timeout. Check your settings, server or internet connection..
        /// </summary>
        public static string Error_Timeout {
            get {
                return ResourceManager.GetString("Error_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Too fast!.
        /// </summary>
        public static string Error_TooFast {
            get {
                return ResourceManager.GetString("Error_TooFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unexcepted error..
        /// </summary>
        public static string Error_UnexceptedError {
            get {
                return ResourceManager.GetString("Error_UnexceptedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP supports only IPv6 or IPv4. Check IP Address..
        /// </summary>
        public static string Error_UnsupportedIP {
            get {
                return ResourceManager.GetString("Error_UnsupportedIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticated.
        /// </summary>
        public static string Info_Authenticated {
            get {
                return ResourceManager.GetString("Info_Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorized!.
        /// </summary>
        public static string Info_Authorized {
            get {
                return ResourceManager.GetString("Info_Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directory changing is unavailable now..
        /// </summary>
        public static string Info_CantChangeDir {
            get {
                return ResourceManager.GetString("Info_CantChangeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Closed..
        /// </summary>
        public static string Info_Closed {
            get {
                return ResourceManager.GetString("Info_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        public static string Info_Connect {
            get {
                return ResourceManager.GetString("Info_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected.
        /// </summary>
        public static string Info_Connected {
            get {
                return ResourceManager.GetString("Info_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting....
        /// </summary>
        public static string Info_Connecting {
            get {
                return ResourceManager.GetString("Info_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create!.
        /// </summary>
        public static string Info_Create {
            get {
                return ResourceManager.GetString("Info_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect.
        /// </summary>
        public static string Info_Disconnect {
            get {
                return ResourceManager.GetString("Info_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnected.
        /// </summary>
        public static string Info_Disconnected {
            get {
                return ResourceManager.GetString("Info_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection closed by MFTP..
        /// </summary>
        public static string Info_Disconnected_by_Prog {
            get {
                return ResourceManager.GetString("Info_Disconnected_by_Prog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection closed by User..
        /// </summary>
        public static string Info_Disconnected_by_User {
            get {
                return ResourceManager.GetString("Info_Disconnected_by_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encoding setted to default value..
        /// </summary>
        public static string Info_Encode_Default {
            get {
                return ResourceManager.GetString("Info_Encode_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Example.txt.
        /// </summary>
        public static string Info_Example {
            get {
                return ResourceManager.GetString("Info_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input new name for New Folder:.
        /// </summary>
        public static string Info_InputNameFolder {
            get {
                return ResourceManager.GetString("Info_InputNameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input new name for File/Folder:.
        /// </summary>
        public static string Info_InputNewName {
            get {
                return ResourceManager.GetString("Info_InputNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Joining....
        /// </summary>
        public static string Info_Joining {
            get {
                return ResourceManager.GetString("Info_Joining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move.
        /// </summary>
        public static string Info_Move {
            get {
                return ResourceManager.GetString("Info_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move there.
        /// </summary>
        public static string Info_MoveThere {
            get {
                return ResourceManager.GetString("Info_MoveThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Folder.
        /// </summary>
        public static string Info_NewFolder {
            get {
                return ResourceManager.GetString("Info_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom port has been saved!.
        /// </summary>
        public static string Info_PortSaved {
            get {
                return ResourceManager.GetString("Info_PortSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename it!.
        /// </summary>
        public static string Info_RenameIt {
            get {
                return ResourceManager.GetString("Info_RenameIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Text_Apply {
            get {
                return ResourceManager.GetString("Text_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto.
        /// </summary>
        public static string Text_Auto {
            get {
                return ResourceManager.GetString("Text_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create File.
        /// </summary>
        public static string Text_CreateFile {
            get {
                return ResourceManager.GetString("Text_CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Folder.
        /// </summary>
        public static string Text_CreateFolder {
            get {
                return ResourceManager.GetString("Text_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom Port.
        /// </summary>
        public static string Text_CustomPort {
            get {
                return ResourceManager.GetString("Text_CustomPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Text_Delete {
            get {
                return ResourceManager.GetString("Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        public static string Text_Download {
            get {
                return ResourceManager.GetString("Text_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string Text_File {
            get {
                return ResourceManager.GetString("Text_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder.
        /// </summary>
        public static string Text_Folder {
            get {
                return ResourceManager.GetString("Text_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FTP Type.
        /// </summary>
        public static string Text_FTPType {
            get {
                return ResourceManager.GetString("Text_FTPType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string Text_Open {
            get {
                return ResourceManager.GetString("Text_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        public static string Text_Password {
            get {
                return ResourceManager.GetString("Text_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        public static string Text_Properties {
            get {
                return ResourceManager.GetString("Text_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional information.
        /// </summary>
        public static string Text_Properties_AddInfo {
            get {
                return ResourceManager.GetString("Text_Properties_AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address:.
        /// </summary>
        public static string Text_Properties_Address {
            get {
                return ResourceManager.GetString("Text_Properties_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advanced:.
        /// </summary>
        public static string Text_Properties_Advanced {
            get {
                return ResourceManager.GetString("Text_Properties_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basic information.
        /// </summary>
        public static string Text_Properties_BasicInfo {
            get {
                return ResourceManager.GetString("Text_Properties_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chmod:.
        /// </summary>
        public static string Text_Properties_Chmod {
            get {
                return ResourceManager.GetString("Text_Properties_Chmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File name:.
        /// </summary>
        public static string Text_Properties_Filename {
            get {
                return ResourceManager.GetString("Text_Properties_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File is unavailable.
        /// </summary>
        public static string Text_Properties_FilenameInvalid {
            get {
                return ResourceManager.GetString("Text_Properties_FilenameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mod. date:.
        /// </summary>
        public static string Text_Properties_ModDate {
            get {
                return ResourceManager.GetString("Text_Properties_ModDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No permissions..
        /// </summary>
        public static string Text_Properties_NoPerms {
            get {
                return ResourceManager.GetString("Text_Properties_NoPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size:.
        /// </summary>
        public static string Text_Properties_Size {
            get {
                return ResourceManager.GetString("Text_Properties_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string Text_Refresh {
            get {
                return ResourceManager.GetString("Text_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename.
        /// </summary>
        public static string Text_Rename {
            get {
                return ResourceManager.GetString("Text_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Text_Settings {
            get {
                return ResourceManager.GetString("Text_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto Encoding.
        /// </summary>
        public static string Text_Settings_AutoEncode {
            get {
                return ResourceManager.GetString("Text_Settings_AutoEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beta functional.
        /// </summary>
        public static string Text_Settings_BetaFunctional {
            get {
                return ResourceManager.GetString("Text_Settings_BetaFunctional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beta functional is unstable, and don&apos;t/bad working and it has been planed in program.
        ///Label colors:
        ///RED: Function isn&apos;t working.
        ///YELLOW: Function unstable.
        ///WHITE: New function, uncategorized(or developer is lazy).
        /// </summary>
        public static string Text_Settings_BetaMessage {
            get {
                return ResourceManager.GetString("Text_Settings_BetaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encoding.
        /// </summary>
        public static string Text_Settings_Encoding {
            get {
                return ResourceManager.GetString("Text_Settings_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Force ASCII.
        /// </summary>
        public static string Text_Settings_ForceASCII {
            get {
                return ResourceManager.GetString("Text_Settings_ForceASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Force UTF7.
        /// </summary>
        public static string Text_Settings_ForceUTF7 {
            get {
                return ResourceManager.GetString("Text_Settings_ForceUTF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Force UTF8.
        /// </summary>
        public static string Text_Settings_ForceUTF8 {
            get {
                return ResourceManager.GetString("Text_Settings_ForceUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FXP Protocol.
        /// </summary>
        public static string Text_Settings_FXPProto {
            get {
                return ResourceManager.GetString("Text_Settings_FXPProto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload.
        /// </summary>
        public static string Text_Upload {
            get {
                return ResourceManager.GetString("Text_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username:.
        /// </summary>
        public static string Text_Username {
            get {
                return ResourceManager.GetString("Text_Username", resourceCulture);
            }
        }
    }
}
