//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _MFTP_.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_MFTP_.Resources.Localizations.ru_RU", typeof(ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пусто.
        /// </summary>
        public static string _null {
            get {
                return ResourceManager.GetString("null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ запрещён..
        /// </summary>
        public static string Error_AccessDenied {
            get {
                return ResourceManager.GetString("Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный адрес. Пример адреса: &quot;C:/Users/Admin/Desktop&quot;.
        /// </summary>
        public static string Error_BadAddress {
            get {
                return ResourceManager.GetString("Error_BadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный порт!.
        /// </summary>
        public static string Error_BadPort {
            get {
                return ResourceManager.GetString("Error_BadPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт не может быть сохранён..
        /// </summary>
        public static string Error_BadPortSave {
            get {
                return ResourceManager.GetString("Error_BadPortSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение принудительно разорвано. Неверный логин или пароль..
        /// </summary>
        public static string Error_Connection_Refused {
            get {
                return ResourceManager.GetString("Error_Connection_Refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение принудительно разорвано..
        /// </summary>
        public static string Error_Connection_Refused_Simple {
            get {
                return ResourceManager.GetString("Error_Connection_Refused_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная директория/файл не найдена..
        /// </summary>
        public static string Error_DirFileNotFound {
            get {
                return ResourceManager.GetString("Error_DirFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует папка по умолчанию... Переходим к списку дисков..
        /// </summary>
        public static string Error_EmptyAddress {
            get {
                return ResourceManager.GetString("Error_EmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка папки..
        /// </summary>
        public static string Error_FolderError {
            get {
                return ResourceManager.GetString("Error_FolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный IP!.
        /// </summary>
        public static string Error_Incorrect_IP {
            get {
                return ResourceManager.GetString("Error_Incorrect_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует соединение с сервером..
        /// </summary>
        public static string Error_IsntConnected {
            get {
                return ResourceManager.GetString("Error_IsntConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один из файлов/директорий не может быть удалён!(вероятно, вы выделили &quot;..&quot; при удалении.).
        /// </summary>
        public static string Error_IsntDeleted {
            get {
                return ResourceManager.GetString("Error_IsntDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один из файлов/директорий не может быть загружен!(вероятно, вы выделили &quot;..&quot; при загрузке.).
        /// </summary>
        public static string Error_IsntDownloaded {
            get {
                return ResourceManager.GetString("Error_IsntDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один из файлов/директорий не может быть перемещён!(вероятно, вы выделили &quot;..&quot; при перемещении.).
        /// </summary>
        public static string Error_IsntMoved {
            get {
                return ResourceManager.GetString("Error_IsntMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл или папка не может быть открыт(а)..
        /// </summary>
        public static string Error_IsntOpened {
            get {
                return ResourceManager.GetString("Error_IsntOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно переименовать файл/директорию!.
        /// </summary>
        public static string Error_IsntRenamed {
            get {
                return ResourceManager.GetString("Error_IsntRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один из файлов/директорий не может быть выгружен!(вероятно, вы выделили &quot;..&quot; при выгрузке.).
        /// </summary>
        public static string Error_IsntUpload {
            get {
                return ResourceManager.GetString("Error_IsntUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка перемещения файла..
        /// </summary>
        public static string Error_MovingError {
            get {
                return ResourceManager.GetString("Error_MovingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт вышел за пределы! Допустимое значение от 0 до 65535..
        /// </summary>
        public static string Error_PortOutOfRange {
            get {
                return ResourceManager.GetString("Error_PortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно обновить списки..
        /// </summary>
        public static string Error_RefreshingUnavailable {
            get {
                return ResourceManager.GetString("Error_RefreshingUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Клиент не подключён к серверу. Обновление списка невозможно..
        /// </summary>
        public static string Error_RefreshingUnavailableServer {
            get {
                return ResourceManager.GetString("Error_RefreshingUnavailableServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите диск..
        /// </summary>
        public static string Error_SelectDisk {
            get {
                return ResourceManager.GetString("Error_SelectDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите диск для того, чтобы загрузить выбранные файлы/папки!.
        /// </summary>
        public static string Error_SelectDiskToDownload {
            get {
                return ResourceManager.GetString("Error_SelectDiskToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка. Указываем адрес на корневой..
        /// </summary>
        public static string Error_SettingAddressDefault {
            get {
                return ResourceManager.GetString("Error_SettingAddressDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время ожидания истекло. Проверьте ваше соединение с сервером и интернетом..
        /// </summary>
        public static string Error_Timeout {
            get {
                return ResourceManager.GetString("Error_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слишком быстро!.
        /// </summary>
        public static string Error_TooFast {
            get {
                return ResourceManager.GetString("Error_TooFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка..
        /// </summary>
        public static string Error_UnexceptedError {
            get {
                return ResourceManager.GetString("Error_UnexceptedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный адрес не поддерживается! Поддерживаются только IPv6 и IPv4..
        /// </summary>
        public static string Error_UnsupportedIP {
            get {
                return ResourceManager.GetString("Error_UnsupportedIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аутентифицирован.
        /// </summary>
        public static string Info_Authenticated {
            get {
                return ResourceManager.GetString("Info_Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизирован!.
        /// </summary>
        public static string Info_Authorized {
            get {
                return ResourceManager.GetString("Info_Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сейчас невозможно изменить директорию..
        /// </summary>
        public static string Info_CantChangeDir {
            get {
                return ResourceManager.GetString("Info_CantChangeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыто..
        /// </summary>
        public static string Info_Closed {
            get {
                return ResourceManager.GetString("Info_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться.
        /// </summary>
        public static string Info_Connect {
            get {
                return ResourceManager.GetString("Info_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключено!.
        /// </summary>
        public static string Info_Connected {
            get {
                return ResourceManager.GetString("Info_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение....
        /// </summary>
        public static string Info_Connecting {
            get {
                return ResourceManager.GetString("Info_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать!.
        /// </summary>
        public static string Info_Create {
            get {
                return ResourceManager.GetString("Info_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключиться.
        /// </summary>
        public static string Info_Disconnect {
            get {
                return ResourceManager.GetString("Info_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединение разорвано..
        /// </summary>
        public static string Info_Disconnected {
            get {
                return ResourceManager.GetString("Info_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединение разорвано программой..
        /// </summary>
        public static string Info_Disconnected_by_Prog {
            get {
                return ResourceManager.GetString("Info_Disconnected_by_Prog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединение разорвано пользователем..
        /// </summary>
        public static string Info_Disconnected_by_User {
            get {
                return ResourceManager.GetString("Info_Disconnected_by_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кодировка была установлена по умолчанию..
        /// </summary>
        public static string Info_Encode_Default {
            get {
                return ResourceManager.GetString("Info_Encode_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.txt.
        /// </summary>
        public static string Info_Example {
            get {
                return ResourceManager.GetString("Info_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название папки.
        /// </summary>
        public static string Info_InputNameFolder {
            get {
                return ResourceManager.GetString("Info_InputNameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите новое название файла\папки.
        /// </summary>
        public static string Info_InputNewName {
            get {
                return ResourceManager.GetString("Info_InputNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключаемся....
        /// </summary>
        public static string Info_Joining {
            get {
                return ResourceManager.GetString("Info_Joining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить.
        /// </summary>
        public static string Info_Move {
            get {
                return ResourceManager.GetString("Info_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить сюда.
        /// </summary>
        public static string Info_MoveThere {
            get {
                return ResourceManager.GetString("Info_MoveThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая папка.
        /// </summary>
        public static string Info_NewFolder {
            get {
                return ResourceManager.GetString("Info_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт был успешно сохранён! .
        /// </summary>
        public static string Info_PortSaved {
            get {
                return ResourceManager.GetString("Info_PortSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переименовать!.
        /// </summary>
        public static string Info_RenameIt {
            get {
                return ResourceManager.GetString("Info_RenameIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string Text_Apply {
            get {
                return ResourceManager.GetString("Text_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авто.
        /// </summary>
        public static string Text_Auto {
            get {
                return ResourceManager.GetString("Text_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать файл.
        /// </summary>
        public static string Text_CreateFile {
            get {
                return ResourceManager.GetString("Text_CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать папку.
        /// </summary>
        public static string Text_CreateFolder {
            get {
                return ResourceManager.GetString("Text_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указать порт.
        /// </summary>
        public static string Text_CustomPort {
            get {
                return ResourceManager.GetString("Text_CustomPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Text_Delete {
            get {
                return ResourceManager.GetString("Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать.
        /// </summary>
        public static string Text_Download {
            get {
                return ResourceManager.GetString("Text_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        public static string Text_File {
            get {
                return ResourceManager.GetString("Text_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка.
        /// </summary>
        public static string Text_Folder {
            get {
                return ResourceManager.GetString("Text_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип FTP подкл..
        /// </summary>
        public static string Text_FTPType {
            get {
                return ResourceManager.GetString("Text_FTPType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        public static string Text_Open {
            get {
                return ResourceManager.GetString("Text_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        public static string Text_Password {
            get {
                return ResourceManager.GetString("Text_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойства.
        /// </summary>
        public static string Text_Properties {
            get {
                return ResourceManager.GetString("Text_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная информация.
        /// </summary>
        public static string Text_Properties_AddInfo {
            get {
                return ResourceManager.GetString("Text_Properties_AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь:.
        /// </summary>
        public static string Text_Properties_Address {
            get {
                return ResourceManager.GetString("Text_Properties_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доп. инф.:.
        /// </summary>
        public static string Text_Properties_Advanced {
            get {
                return ResourceManager.GetString("Text_Properties_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Базовая информация.
        /// </summary>
        public static string Text_Properties_BasicInfo {
            get {
                return ResourceManager.GetString("Text_Properties_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chmod:.
        /// </summary>
        public static string Text_Properties_Chmod {
            get {
                return ResourceManager.GetString("Text_Properties_Chmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла:.
        /// </summary>
        public static string Text_Properties_Filename {
            get {
                return ResourceManager.GetString("Text_Properties_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл недоступен..
        /// </summary>
        public static string Text_Properties_FilenameInvalid {
            get {
                return ResourceManager.GetString("Text_Properties_FilenameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата мод.:.
        /// </summary>
        public static string Text_Properties_ModDate {
            get {
                return ResourceManager.GetString("Text_Properties_ModDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет прав..
        /// </summary>
        public static string Text_Properties_NoPerms {
            get {
                return ResourceManager.GetString("Text_Properties_NoPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер:.
        /// </summary>
        public static string Text_Properties_Size {
            get {
                return ResourceManager.GetString("Text_Properties_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Text_Refresh {
            get {
                return ResourceManager.GetString("Text_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переименовать.
        /// </summary>
        public static string Text_Rename {
            get {
                return ResourceManager.GetString("Text_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Text_Settings {
            get {
                return ResourceManager.GetString("Text_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авто кодировка.
        /// </summary>
        public static string Text_Settings_AutoEncode {
            get {
                return ResourceManager.GetString("Text_Settings_AutoEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бета функции.
        /// </summary>
        public static string Text_Settings_BetaFunctional {
            get {
                return ResourceManager.GetString("Text_Settings_BetaFunctional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бета функционал нестабилен, он может работать или работать плохо/нестабильно. 
        ///Пометки цветом:
        ///Красный: Функция не работает.
        ///Желтый:Функция нестабильна.
        ///Белый:Новая функция без категории(или разработчику было лень указать).
        /// </summary>
        public static string Text_Settings_BetaMessage {
            get {
                return ResourceManager.GetString("Text_Settings_BetaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кодировка.
        /// </summary>
        public static string Text_Settings_Encoding {
            get {
                return ResourceManager.GetString("Text_Settings_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принуд. ASCII.
        /// </summary>
        public static string Text_Settings_ForceASCII {
            get {
                return ResourceManager.GetString("Text_Settings_ForceASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принуд. UTF7.
        /// </summary>
        public static string Text_Settings_ForceUTF7 {
            get {
                return ResourceManager.GetString("Text_Settings_ForceUTF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принуд. UTF8.
        /// </summary>
        public static string Text_Settings_ForceUTF8 {
            get {
                return ResourceManager.GetString("Text_Settings_ForceUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FXP Протокол.
        /// </summary>
        public static string Text_Settings_FXPProto {
            get {
                return ResourceManager.GetString("Text_Settings_FXPProto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string Text_Settings_Language {
            get {
                return ResourceManager.GetString("Text_Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение языка происходит не мгновенно! Требуется перезагрузка..
        /// </summary>
        public static string Text_Settings_LanguageMessage {
            get {
                return ResourceManager.GetString("Text_Settings_LanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другое.
        /// </summary>
        public static string Text_Settings_Other {
            get {
                return ResourceManager.GetString("Text_Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string Text_Upload {
            get {
                return ResourceManager.GetString("Text_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин:.
        /// </summary>
        public static string Text_Username {
            get {
                return ResourceManager.GetString("Text_Username", resourceCulture);
            }
        }
    }
}
